# Welcome to Jekyll!
#

# Site settings
title: fair-list 
description: |
  Save money. Go Agentless™.
owner: fair-list inc. # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: info@fair-list.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.fair-list.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/fair_list
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #instagram:
  #angellist:
  #stackexchange:
  #slack:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Google Analytics Token
google_analytics: UA-120909028-1 
google_adwords: AW-801345477

# Amazon Alexa
alexa_account: duVrr1O7kI20L7
alexa_domain: fair-list.com

# Gems
plugins:
 - jekyll-redirect-from
 - jekyll-sitemap

# Collections
# WARNING: Identifying a specific collection through the site variable is currently
#          broken. These documents will be _generated_, but not programmatically 
#          accessible.
collections:
  guides:
    output: true

